feat: add GitHub Actions workflow for building and signing Windows and Linux binaries

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -166,43 +166,47 @@ jobs:
           fetch-depth: 0
 
       - name: GPG Import
-        if: github.event_name != 'pull_request' && secrets.PUB_ASC != ''
+        if: github.event_name != 'pull_request'
         run: |
-          # Import the public key
-          gpg --batch --yes --import <(echo "${{ secrets.PUB_ASC }}")
-          if [[ $? -ne 0 ]]; then
-            echo "Error: Failed to import the public key"
-            exit 1
-          fi
-          
-          # Import the private key
-          gpg --batch --yes --import <(echo "${{ secrets.KEY_ASC }}")
-          if [[ $? -ne 0 ]]; then
-            echo "Error: Failed to import the private key"
-            exit 2
-          fi
-          
-          # Extract the fingerprint of the imported public key
-          GPG_LINUX_FINGERPRINT=$(gpg --list-keys --with-colons | grep '^fpr' | head -n 1 | cut -d: -f10)
-          
-          # Check if the fingerprint was extracted
-          if [[ -z "$GPG_LINUX_FINGERPRINT" ]]; then
-            echo "Error: Failed to extract the fingerprint of the key"
-            exit 3
-          fi
-          
-          # Set the trust level for the key
-          echo "$GPG_LINUX_FINGERPRINT:6:" | gpg --batch --import-ownertrust
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to set trust for the key $GPG_LINUX_FINGERPRINT"
-            exit 4
-          fi
-          
-          echo "Key $GPG_LINUX_FINGERPRINT successfully imported and trusted"
-          gpg --list-keys
+          if [ -n "${{ secrets.PUB_ASC }}" ]; then
+            # Import the public key
+            gpg --batch --yes --import <(echo "${{ secrets.PUB_ASC }}")
+            if [[ $? -ne 0 ]]; then
+              echo "Error: Failed to import the public key"
+              exit 1
+            fi
+            
+            # Import the private key
+            gpg --batch --yes --import <(echo "${{ secrets.KEY_ASC }}")
+            if [[ $? -ne 0 ]]; then
+              echo "Error: Failed to import the private key"
+              exit 2
+            fi
+            
+            # Extract the fingerprint of the imported public key
+            GPG_LINUX_FINGERPRINT=$(gpg --list-keys --with-colons | grep '^fpr' | head -n 1 | cut -d: -f10)
+            
+            # Check if the fingerprint was extracted
+            if [[ -z "$GPG_LINUX_FINGERPRINT" ]]; then
+              echo "Error: Failed to extract the fingerprint of the key"
+              exit 3
+            fi
+            
+            # Set the trust level for the key
+            echo "$GPG_LINUX_FINGERPRINT:6:" | gpg --batch --import-ownertrust
+            if [ $? -ne 0 ]; then
+              echo "Error: Failed to set trust for the key $GPG_LINUX_FINGERPRINT"
+              exit 4
+            fi
+            
+            echo "Key $GPG_LINUX_FINGERPRINT successfully imported and trusted"
+            gpg --list-keys
 
-          #export for global use
-          echo "GPG_LINUX_FINGERPRINT=$GPG_LINUX_FINGERPRINT" >> $GITHUB_ENV
+            #export for global use
+            echo "GPG_LINUX_FINGERPRINT=$GPG_LINUX_FINGERPRINT" >> $GITHUB_ENV
+          else
+            echo "GPG keys not provided, skipping signature."
+          fi
         shell: bash
 
       - name: Build
