ci: add GitHub Actions workflow for building and packaging Windows and Linux binaries

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -166,6 +166,7 @@ jobs:
           fetch-depth: 0
 
       - name: GPG Import
+        if: github.event_name != 'pull_request' && secrets.PUB_ASC != ''
         run: |
           # Import the public key
           gpg --batch --yes --import <(echo "${{ secrets.PUB_ASC }}")
@@ -203,7 +204,6 @@ jobs:
           #export for global use
           echo "GPG_LINUX_FINGERPRINT=$GPG_LINUX_FINGERPRINT" >> $GITHUB_ENV
         shell: bash
-        if: github.event_name != 'pull_request'
 
       - name: Build
         run: |
@@ -277,26 +277,31 @@ jobs:
           startsWith(github.ref, 'refs/tags/')
         run: |
         
-          # new runner, niw signs
-          gpg --batch --yes --import <(echo "${{ secrets.PUB_ASC }}")
-          gpg --batch --yes --import <(echo "${{ secrets.KEY_ASC }}")
-          GPG_LINUX_FINGERPRINT=$(gpg --list-keys --with-colons | grep '^fpr' | head -n 1 | cut -d: -f10)
-          echo "$GPG_LINUX_FINGERPRINT:6:" | gpg --batch --import-ownertrust
-          echo "GPG_LINUX_FINGERPRINT=$GPG_LINUX_FINGERPRINT" >> $GITHUB_ENV
-
-          sign_file() {
-            local file=$1
-            gpg --batch --yes --detach-sign --armor -u "$GPG_LINUX_FINGERPRINT" "$file"
-            if [ $? -ne 0 ]; then
-              echo "Error: Failed to sign $file"
-              exit 2
-            fi
-            echo "$file signed successfully."
-          }
-          
-          # Pack and sign final archive
+          # Pack final archive
           7z a -tzip reapi-bin-${{ needs.linux.outputs.app-version }}.zip addons/
-          sign_file "reapi-bin-${{ needs.linux.outputs.app-version }}.zip"
+          
+          # new runner, niw signs
+          if [ -n "${{ secrets.PUB_ASC }}" ]; then
+            gpg --batch --yes --import <(echo "${{ secrets.PUB_ASC }}")
+            gpg --batch --yes --import <(echo "${{ secrets.KEY_ASC }}")
+            GPG_LINUX_FINGERPRINT=$(gpg --list-keys --with-colons | grep '^fpr' | head -n 1 | cut -d: -f10)
+            echo "$GPG_LINUX_FINGERPRINT:6:" | gpg --batch --import-ownertrust
+            echo "GPG_LINUX_FINGERPRINT=$GPG_LINUX_FINGERPRINT" >> $GITHUB_ENV
+
+            sign_file() {
+              local file=$1
+              gpg --batch --yes --detach-sign --armor -u "$GPG_LINUX_FINGERPRINT" "$file"
+              if [ $? -ne 0 ]; then
+                echo "Error: Failed to sign $file"
+                exit 2
+              fi
+              echo "$file signed successfully."
+            }
+
+            sign_file "reapi-bin-${{ needs.linux.outputs.app-version }}.zip"
+          else
+            echo "GPG keys not provided, skipping signature."
+          fi
 
       - name: Publish artifacts
         uses: softprops/action-gh-release@v2
